classdef TabButtonLight < uim.style.ButtonScheme

    properties (Constant)

        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', uim.style.TabButtonLight.getFocusColor(), ...
            'BackgroundAlpha', 0.9, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.6)
        HighlightedOff = struct(...
            'ForegroundColor', 1 - ones(1,3) * 0.95, ...
            'BackgroundColor', ones(1,3)*0.82, ...
            'BackgroundAlpha', 0.6, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        On = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', uim.style.TabButtonLight.getFocusColor(), ...
            'BackgroundAlpha', 0.8, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        Off = struct(...
            'ForegroundColor', 1 - ones(1,3) * 0.8, ...
            'BackgroundColor', 1 - ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
    end

    methods (Static)
        function rgb = getFocusColor
            rgb = [0.0000, 0.4470, 0.7410];
        end
    end
end
